package com.example.gridlott;

import javafx.animation.PathTransition;
import javafx.animation.PauseTransition;
import javafx.application.Platform;
import javafx.beans.property.*;
import javafx.geometry.Bounds;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.Tooltip;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.shape.*;
import javafx.util.Duration;

import java.awt.Point;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

import static com.example.gridlott.GridlottUI.parkingTicketNumber;

public class ParkingLot {
    //LAYOUT CONSTANTS
    private static final double CELL_WIDTH = 40.0;
    private static final double CELL_HEIGHT = 70.0;
    private static final String BACKGROUND_HEX = "#1a1a1a";

    //ANIMATION DURATION SETTINGS
    private static final double TIME_ORIGIN_EXIT = 0.4;
    private static final double TIME_INTERMEDIATE_LOOP = 3.5;
    private static final double TIME_GROUND_CROSS = 1.5;
    private static final double TIME_LOT_EXIT = 1.2;

    //STRUCTURAL STATES
    private int floors = 1;
    private boolean rampsEnabled = false;
    private final int rows, cols;
    private Vehicle[][][] occupancy;
    private StackPane[][][] spotUI;
    private final List<List<Queue<Point>>> floorStructuralZones = new ArrayList<>();
    private int activeZoneTurn = 0;

    //UI LAYOUT CONTAINERS
    private final Pane layeredCanvas = new Pane();
    private final List<GridPane> floorGrids = new ArrayList<>();
    private final List<Pane> pathOverlayLayers = new ArrayList<>(); //overlay vector sheets for structural paths
    private int currentlyViewedFloor = 0;

    //DASHBOARDUI VARIABLES
    private boolean useBottomLeftGateNext = true;
    private boolean useTopRightExitNext = false;
    private final DoubleProperty totalRevenue = new SimpleDoubleProperty(0.0);
    private final IntegerProperty currentOccupancy = new SimpleIntegerProperty(0);
    private final IntegerProperty totalCars = new SimpleIntegerProperty(0);
    private final DateTimeFormatter logTimeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    //THIS IS ESSENTIAL FOR STOPPING ANY GHOST TRANSITIONS WHEN NEW LOTS ARE GENERATED BY SETTING CHANGES WHILE PROGRAM IS RUNNING
    private final java.util.List<javafx.animation.Animation> activeAnimations = new java.util.ArrayList<>();

    //LOGGERS===========================================================================================================

    //dedicated for GridLottUI to rely on this to link with ParkingLot updates
    public interface LogListener {
        void onLogEvent(javafx.scene.paint.Paint dotColor, String plate, boolean isEntry, int row, int col, int floor);
    }
    private LogListener logListener;

    public void setLogListener(LogListener logListener) {
        this.logListener = logListener;
    }
    //==================================================================================================================

    //STRUCTURAL INITIALIZATIONS AND UI GENERATIONS=====================================================================

    public record FloorPoint(int floor, int x, int y) {}

    public ParkingLot(int rows, int cols) {//CONSTRUCTOR
        this.rows = rows;
        this.cols = cols;
    }

    public void setFloorCount(int count) {
        if (count < 1) throw new IllegalArgumentException("Parking lot must have at least 1 floor!");
        this.floors = count;
        this.rampsEnabled = (count > 1);
        this.initializeStructures();
    }

    //initializations for main components for grid and setting up queues for vehicles to determine which spots to go to
    private void initializeStructures() {
        this.occupancy = new Vehicle[floors][cols][rows];
        this.spotUI = new StackPane[floors][cols][rows];
        this.floorStructuralZones.clear();
        this.floorGrids.clear();
        this.pathOverlayLayers.clear();

        int zoneWidth = (int) Math.ceil((double) cols / 3);

        for (int f = 0; f < floors; f++) {
            floorStructuralZones.add(List.of(new ArrayDeque<>(), new ArrayDeque<>(), new ArrayDeque<>()));

            List<Point> masterList = new ArrayList<>();
            for (int c = 0; c < cols; c++) {
                for (int r = 0; r < rows; r++) {
                    masterList.add(new Point(c, r));
                }
            }
            Collections.shuffle(masterList);

            for (Point p : masterList) {
                int zoneId = Math.min(p.x / zoneWidth, 2);
                floorStructuralZones.get(f).get(zoneId).add(p);
            }

            GridPane grid = new GridPane();
            floorGrids.add(grid);

            Pane overlay = new Pane();
            overlay.setMouseTransparent(true);
            pathOverlayLayers.add(overlay);

            layeredCanvas.getChildren().addAll(grid, overlay);
        }

        floorGrids.get(0).boundsInLocalProperty().addListener((obs, oldBounds, newBounds) -> {
            layeredCanvas.setPrefSize(newBounds.getWidth(), newBounds.getHeight());
            layeredCanvas.setMaxSize(newBounds.getWidth(), newBounds.getHeight());
        });
    }

    //actually builds the grid or parking lot in the UI
    public void generateParkingLot() {
        for (int f = 0; f < floors; f++) {

            final int floorIndex = f;

            GridPane grid = floorGrids.get(f);
            configureGridStyle(grid, f == 0);

            for (int r = 0; r < rows; r++) {
                for (int c = 0; c < cols; c++) {
                    StackPane spot = createParkingStall(r);
                    grid.add(spot, c, r);
                    spotUI[f][c][r] = spot;
                }
            }

            //whenever the grid changes size/position, refresh the paths if enabled
            grid.boundsInParentProperty().addListener((obs, oldBounds, newBounds) -> {
                if (Config.showPaths && floorIndex== currentlyViewedFloor) {
                    Platform.runLater(() -> renderFloorPaths(currentlyViewedFloor));
                }
            });

        }
    }

    private void configureGridStyle(GridPane grid, boolean isGroundFloor) {
        grid.setStyle("-fx-background-color: #131314;");
        grid.setPadding(new Insets(30, 40, 30, 40));
        grid.setHgap(0);
        grid.setVgap(0);
        grid.setAlignment(Pos.CENTER);
        if (!isGroundFloor) {
            grid.setVisible(false);
            grid.setMouseTransparent(true);
        }
    }

    private StackPane createParkingStall(int row) {
        Rectangle stall = new Rectangle(CELL_WIDTH, CELL_HEIGHT);
        stall.setFill(Color.TRANSPARENT);
        stall.setStroke(Color.web("#2d2d30"));
        stall.setStrokeWidth(0.8);
        stall.setMouseTransparent(true);

        StackPane spot = new StackPane(stall);
        int bottomMargin = (row % 2 == 0) ? 0 : 25;
        GridPane.setMargin(spot, new Insets(0, 1, bottomMargin, 1));
        return spot;
    }
    //==================================================================================================================

    //DYNAMIC VISIBILITY MANAGEMENT ENGINE==============================================================================

    //essential for scrolling through floors in the UI depending on which floor the user is looking at
    public void showFloor(int floorIndex) {
        this.currentlyViewedFloor = floorIndex;

        for (int f = 0; f < floors; f++) {
            boolean isTarget = (f == floorIndex);
            floorGrids.get(f).setVisible(isTarget);
            floorGrids.get(f).setMouseTransparent(!isTarget);

            if (f < pathOverlayLayers.size()) {
                pathOverlayLayers.get(f).getChildren().clear();
                if (isTarget && Config.showPaths) {
                    renderFloorPaths(floorIndex);
                }
            }
        }
        syncAllDotsVisibility();
    }

    //depending on the viewing floor chosen by the user, it will update each dot's movement
    //in the following two methods here
    private void syncAllDotsVisibility() {
        for (javafx.scene.Node node : layeredCanvas.getChildren()) {
            if (node instanceof Circle dot) {
                updateDotVisibilityState(dot);
            }
        }
    }

    private void updateDotVisibilityState(Circle dot) {
        Integer currentPhysicalFloor = (Integer) dot.getProperties().get("currentPhysicalFloor");
        if (currentPhysicalFloor != null) {
            dot.setVisible(currentPhysicalFloor == currentlyViewedFloor);
        }
    }

    //shows the pathing of where dot's traverse to if enabled in Config class
    public void renderFloorPaths(int floorIndex) {
        Pane currentOverlay = pathOverlayLayers.get(floorIndex);
        currentOverlay.getChildren().clear();

        if (!Config.showPaths) return; //immediate exit if disabled this line is new

        //force the node to compute its layout bounds immediately
        floorGrids.get(floorIndex).applyCss();
        floorGrids.get(floorIndex).layout();

        Bounds first = spotUI[floorIndex][0][0].getBoundsInParent();
        Bounds last = spotUI[floorIndex][cols - 1][rows - 1].getBoundsInParent();

        //if the bounds are still (0,0,0,0), this means it's too early;
        //the listener will catch the next update when they become non-zero.
        if (first.getWidth() == 0) return;

        double leftX = first.getMinX() - 20.0;
        double rightX = last.getMaxX() + 20.0;

        double topAisleY = determineAisleY(0, 0, first);
        double bottomAisleY = determineAisleY(rows - 1, 0, first);

        Path redRoadNetwork = new Path();
        redRoadNetwork.setStroke(Color.web("#39FF14"));
        redRoadNetwork.setStrokeWidth(2.0);
        redRoadNetwork.setOpacity(1);

        //draw the main vertical spine lines
        redRoadNetwork.getElements().addAll(
                new MoveTo(leftX, topAisleY),
                new LineTo(leftX, bottomAisleY),
                new MoveTo(rightX, topAisleY),
                new LineTo(rightX, bottomAisleY)
        );

        //adds the top gate tail (for every floor)
        Bounds topGate = spotUI[floorIndex][cols-1][0].getBoundsInParent();
        double extensionOffsets = topGate.getHeight() - 30; //adjust this value to match your spacing
        redRoadNetwork.getElements().addAll(
                new MoveTo(rightX, topAisleY),
                new LineTo(rightX, topAisleY - extensionOffsets)
        );

        double extension = first.getHeight() * (1.0 - (30.0 / first.getHeight())); //draws the top left tail for ramp
        double rampEndPointX = last.getMaxX() - (first.getWidth() * 0.5); //this is where dots disappear to go up a floor
        boolean hasMultipleFloors = Config.floors > 1; //check if we have more than one floor; if so, we need ramps

        if (floorIndex == 0) {
            //logic for bottom gate tail (always execute for floor 0)
            double extensionOffset = (Config.rows % 2 == 1) ? 32 : -50;
            Bounds bottomGate = spotUI[floorIndex][0][rows - 1].getBoundsInParent();
            redRoadNetwork.getElements().addAll(
                    new MoveTo(leftX, bottomAisleY),
                    new LineTo(leftX, bottomAisleY + bottomGate.getHeight() + extensionOffset)
            );

            //if there are multiple floors
            if (hasMultipleFloors) {
                redRoadNetwork.getElements().addAll(
                        new MoveTo(leftX, topAisleY),
                        new LineTo(leftX, topAisleY - extension),
                        new LineTo(rampEndPointX, topAisleY - extension)
                );
            }

        } else if (floorIndex < Config.floors - 1) {
            //any intermediate floor (always has a ramp) or floors between floor 1 and last floor
            redRoadNetwork.getElements().addAll(
                    new MoveTo(leftX, topAisleY),
                    new LineTo(leftX, topAisleY - extension),
                    new LineTo(rampEndPointX, topAisleY - extension)
            );
        } //simply means if last floor, don't add ramps

        for (int r = 0; r < rows; r++) { //draw aisles and vertical connectors to each cell
            double aisleY = determineAisleY(r, 0, first);
            redRoadNetwork.getElements().addAll(new MoveTo(leftX, aisleY), new LineTo(rightX, aisleY));

            for (int c = 0; c < cols; c++) {
                Bounds spot = spotUI[floorIndex][c][r].getBoundsInParent();
                double centerX = spot.getMinX() + (spot.getWidth() / 2);
                redRoadNetwork.getElements().addAll(
                        new MoveTo(centerX, aisleY),
                        new LineTo(centerX, spot.getMinY() + (spot.getHeight()/2))
                );
            }
        }
        currentOverlay.getChildren().add(redRoadNetwork);
    }

    //==================================================================================================================

    //VEHICLE ARRIVAL & PATH ROUTING SIMULATION=========================================================================
    public void simulateParking(Vehicle v, ParkRate rate, RandomizeDuration p, int ticketNumber) {
        FloorPoint target = checkMultiFloorTarget();
        if (target == null) return;

        int targetFloor = target.floor();
        int targetCol = target.x();
        int targetRow = target.y();

        v.setTicketNumber(ticketNumber);
        parkingTicketNumber++; //increment GridLott var for upcoming vehicles
        occupancy[targetFloor][targetCol][targetRow] = v;

        Bounds targetStallBounds = spotUI[0][targetCol][targetRow].getBoundsInParent();
        Bounds firstCellBounds = spotUI[0][0][0].getBoundsInParent();
        Bounds lastCellBounds = spotUI[0][cols - 1][rows - 1].getBoundsInParent();

        double cellCenterX = targetStallBounds.getMinX() + (targetStallBounds.getWidth() / 2.0);
        double cellCenterY = targetStallBounds.getMinY() + (targetStallBounds.getHeight() / 2.0);
        double chosenAisleY = determineAisleY(targetRow, targetCol, firstCellBounds);

        double leftLaneX = firstCellBounds.getMinX() - (firstCellBounds.getWidth() * 0.5);
        double rightLaneX = lastCellBounds.getMaxX() + (firstCellBounds.getWidth() * 0.5);
        double bottomRoadY = lastCellBounds.getMaxY() + (firstCellBounds.getHeight() * 0.4);

        double switchbackUpperY = firstCellBounds.getMinY() - (firstCellBounds.getHeight() * 0.815);
        double switchbackLowerY = determineAisleY(0,0, firstCellBounds);
        double rampEndPointX = lastCellBounds.getMaxX() - (firstCellBounds.getWidth() * 0.5);

        boolean assignedToBottomLeft = useBottomLeftGateNext;
        useBottomLeftGateNext = !useBottomLeftGateNext;

        Circle dot = v.getDot();
        Boolean c = Config.betterDotVisuals;
        assignVehicleColor(dot, targetFloor, c);

        try {
            if (logListener != null) {
                logListener.onLogEvent(dot.getFill(), v.getPlate(), true, targetRow, targetCol, targetFloor);
            }
        } catch (Exception ex) {
            System.err.println("Logging failed, but keeping loop alive: " + ex.getMessage());
        }

        if (assignedToBottomLeft) {
            dot.setTranslateX(leftLaneX);
            dot.setTranslateY(bottomRoadY);
        } else {
            dot.setTranslateX(rightLaneX);
            dot.setTranslateY(switchbackUpperY);
        }

        dot.getProperties().put("targetFloor", targetFloor);
        dot.getProperties().put("currentPhysicalFloor", 0);
        layeredCanvas.getChildren().add(dot);
        updateDotVisibilityState(dot);

        Path entryPath = new Path();
        double duration = 2.0;

        if (assignedToBottomLeft) {
            entryPath.getElements().add(new MoveTo(leftLaneX, bottomRoadY));
            if (rampsEnabled && targetFloor > 0) {
                entryPath.getElements().add(new LineTo(leftLaneX, switchbackUpperY));
                entryPath.getElements().add(new LineTo(rampEndPointX, switchbackUpperY));
            } else {
                entryPath.getElements().add(new LineTo(leftLaneX, chosenAisleY));
                entryPath.getElements().add(new LineTo(cellCenterX, chosenAisleY));
                entryPath.getElements().add(new LineTo(cellCenterX, cellCenterY));
            }
        } else {
            entryPath.getElements().add(new MoveTo(rightLaneX, switchbackUpperY));
            if (rampsEnabled && targetFloor > 0) {
                entryPath.getElements().add(new LineTo(rightLaneX, switchbackLowerY));
                entryPath.getElements().add(new LineTo(leftLaneX, switchbackLowerY));
                entryPath.getElements().add(new LineTo(leftLaneX, switchbackUpperY));
                entryPath.getElements().add(new LineTo(rampEndPointX, switchbackUpperY));
                duration = 3.2;
            } else {
                entryPath.getElements().add(new LineTo(rightLaneX, chosenAisleY));
                entryPath.getElements().add(new LineTo(cellCenterX, chosenAisleY));
                entryPath.getElements().add(new LineTo(cellCenterX, cellCenterY));
            }
        }

        PathTransition entryEngine = new PathTransition(Duration.seconds(duration / Config.speedMultiplier), entryPath, dot);

        activeAnimations.add(entryEngine);  //TRACK DRIVING ANIMATION essential for managing ghost cars

        entryEngine.setOnFinished(e -> {
            activeAnimations.remove(entryEngine); //REMOVE FROM TRACKING UPON NATURAL COMPLETION

            if (targetFloor > 0 && rampsEnabled) {
                chainUpwardRampClimb(dot, 1, targetFloor, leftLaneX, rightLaneX, switchbackUpperY, switchbackLowerY,
                        chosenAisleY, cellCenterX, cellCenterY, v, targetCol, targetRow, p, rate, bottomRoadY, assignedToBottomLeft);
            } else {
                finalizeArrivalState(v, targetFloor, targetCol, targetRow, p, rate, cellCenterX, cellCenterY, chosenAisleY,
                        leftLaneX, rightLaneX, switchbackUpperY, switchbackLowerY, bottomRoadY, assignedToBottomLeft);
            }
        });
        entryEngine.play();
    }

    private void assignVehicleColor(Circle dot, int targetFloor, Boolean c) {
        if(c){
            switch (targetFloor) {
                case 0 -> dot.setFill(Color.web("#FFD700"));
                case 1 -> dot.setFill(Color.web("#9370DB"));
                case 2 -> dot.setFill(Color.web("#00FFFF"));
                case 3 -> dot.setFill(Color.web("#FF0000"));
                default -> dot.setFill(Color.web("#800080"));
            }
        }

        //if(c){
            //for(int i = 0; i < targetFloor; i++){
                //Random rand = new Random();
                //dot.setFill(Color.rgb(rand.nextInt(256), rand.nextInt(256), rand.nextInt(256)));
            //}
        //}
    }

    //RECURSIVE MULTI-FLOOR UPWARD CLIMB ENGINE
    private void chainUpwardRampClimb(Circle dot, int currentLevel, int targetFloor, double leftLaneX, double rightLaneX,
                                      double switchbackUpperY, double switchbackLowerY, double finalAisleY, double cellCenterX,
                                      double cellCenterY, Vehicle v, int finalCol, int finalRow, RandomizeDuration p,
                                      ParkRate rate, double bottomRoadY, boolean cameFromLeftGate) {

        dot.getProperties().put("currentPhysicalFloor", currentLevel);
        updateDotVisibilityState(dot);

        Bounds firstCellBounds = spotUI[0][0][0].getBoundsInParent();
        Bounds lastCellBounds = spotUI[0][cols - 1][0].getBoundsInParent();
        double rampEndPointX = lastCellBounds.getMaxX() - (firstCellBounds.getWidth() * 0.5);

        if (currentLevel < targetFloor) {
            Path transitPath = new Path();
            transitPath.getElements().add(new MoveTo(rightLaneX, switchbackUpperY));
            transitPath.getElements().add(new LineTo(rightLaneX, switchbackLowerY));
            transitPath.getElements().add(new LineTo(leftLaneX, switchbackLowerY));
            transitPath.getElements().add(new LineTo(leftLaneX, switchbackUpperY));
            transitPath.getElements().add(new LineTo(rampEndPointX, switchbackUpperY));

            PathTransition engine = new PathTransition(Duration.seconds(3.5 / Config.speedMultiplier), transitPath, dot);

            activeAnimations.add(engine); //TRACK CLIMBING ANIMATION

            engine.setOnFinished(ev -> {
                activeAnimations.remove(engine);
                chainUpwardRampClimb(dot, currentLevel + 1, targetFloor, leftLaneX, rightLaneX,
                        switchbackUpperY, switchbackLowerY, finalAisleY, cellCenterX, cellCenterY, v, finalCol, finalRow,
                        p, rate, bottomRoadY, cameFromLeftGate);
            });
            engine.play();
        } else {
            Path arrivalPath = new Path();
            arrivalPath.getElements().add(new MoveTo(rightLaneX, switchbackLowerY));

            if (cameFromLeftGate && finalRow == 0) {
                arrivalPath.getElements().add(new LineTo(cellCenterX, switchbackLowerY));
                arrivalPath.getElements().add(new LineTo(cellCenterX, finalAisleY));
            } else {
                arrivalPath.getElements().add(new LineTo(rightLaneX, finalAisleY));
                arrivalPath.getElements().add(new LineTo(cellCenterX, finalAisleY));
            }
            arrivalPath.getElements().add(new LineTo(cellCenterX, cellCenterY));

            PathTransition arrivalEngine = new PathTransition(Duration.seconds(2.5 / Config.speedMultiplier), arrivalPath, dot);

            activeAnimations.add(arrivalEngine); //TRACK CLIMB ARRIVAL ANIMATION

            arrivalEngine.setOnFinished(ev -> {
                activeAnimations.remove(arrivalEngine);
                finalizeArrivalState(v, targetFloor, finalCol, finalRow, p, rate, cellCenterX, cellCenterY, finalAisleY,
                        leftLaneX, rightLaneX, switchbackUpperY, switchbackLowerY, bottomRoadY, cameFromLeftGate);
            });
            arrivalEngine.play();
        }
    }

    //PARKING STAY STATE STAY & SEQUENTIAL DESCENT SYSTEM
    private void finalizeArrivalState(Vehicle v, int finalFloor, int finalCol, int finalRow, RandomizeDuration p,
                                      ParkRate rate, double cellCenterX, double cellCenterY, double finalAisleY,
                                      double leftLaneX, double rightLaneX, double switchbackUpperY, double switchbackLowerY,
                                      double bottomRoadY, boolean finalGateChoice) {

        currentOccupancy.set(currentOccupancy.get() + 1);
        totalCars.set(totalCars.get() + 1);

        Circle dot = v.getDot();
        dot.getProperties().put("currentPhysicalFloor", finalFloor);
        updateDotVisibilityState(dot);

        final double calculatedStayDuration = p.getRandomizeDuration();

        v.calculateWaitTimes(calculatedStayDuration);

        PauseTransition stayTimer = new PauseTransition(Duration.seconds(v.getInitialWait()));
        activeAnimations.add(stayTimer); //TRACK PARKED STAY TIMER

        stayTimer.setOnFinished(stayEvent -> {
            activeAnimations.remove(stayTimer);

            if(Config.showDotGlow){
                v.triggerExitPulse(); //trigger pulse effect (this means this vehicle is about to exit)
            }

            //start the final 2-second countdown buffer
            PauseTransition exitBuffer = new PauseTransition(Duration.seconds(v.getWarningTime()));
            activeAnimations.add(exitBuffer);

            exitBuffer.setOnFinished(exBufferEvent -> {
                activeAnimations.remove(exitBuffer);

                occupancy[finalFloor][finalCol][finalRow] = null;
                currentOccupancy.set(currentOccupancy.get() - 1);

                Path stallExitPath = new Path();
                stallExitPath.getElements().add(new MoveTo(cellCenterX, cellCenterY));

                if (rampsEnabled && finalFloor > 0) {
                    stallExitPath.getElements().add(new LineTo(cellCenterX, finalAisleY));
                    stallExitPath.getElements().add(new LineTo(rightLaneX, finalAisleY));
                    stallExitPath.getElements().add(new LineTo(rightLaneX, switchbackLowerY));
                } else {
                    if (finalGateChoice) {
                        stallExitPath.getElements().add(new LineTo(cellCenterX, finalAisleY));
                        stallExitPath.getElements().add(new LineTo(leftLaneX, finalAisleY));
                        stallExitPath.getElements().add(new LineTo(leftLaneX, bottomRoadY));
                    } else {
                        if (finalRow == 0) {
                            stallExitPath.getElements().add(new LineTo(cellCenterX, switchbackLowerY));
                            stallExitPath.getElements().add(new LineTo(rightLaneX, switchbackLowerY));
                        } else {
                            stallExitPath.getElements().add(new LineTo(cellCenterX, finalAisleY));
                            stallExitPath.getElements().add(new LineTo(rightLaneX, finalAisleY));
                            stallExitPath.getElements().add(new LineTo(rightLaneX, switchbackLowerY));
                        }
                    }
                }

                PathTransition exitEngine = new PathTransition(Duration.seconds(2.0 / Config.speedMultiplier), stallExitPath, dot);

                activeAnimations.add(exitEngine); //TRACK STALL EXIT ANIMATION

                exitEngine.setOnFinished(ex -> {
                    activeAnimations.remove(exitEngine);

                    if (finalFloor > 0 && rampsEnabled) {
                        chainDownwardRampDescent(dot, finalFloor, bottomRoadY, leftLaneX, rightLaneX, switchbackUpperY,
                                switchbackLowerY, v, finalFloor, finalCol, finalRow, rate, calculatedStayDuration, finalGateChoice);
                    } else {
                        completeCleanUp(v, finalFloor, finalCol, finalRow, rate, calculatedStayDuration);
                    }
                });
                exitEngine.play();
            });
            exitBuffer.play();
        });
        stayTimer.play();
    }

    //lets vehicles traverse down floors with ramps no matter what floor they are currently in
    private void chainDownwardRampDescent(Circle dot, int currentLevel, double bottomRoadY, double leftLaneX,
                                          double rightLaneX, double switchbackUpperY, double switchbackLowerY,
                                          Vehicle v, int finalFloor, int finalCol, int finalRow, ParkRate rate,
                                          double parkingStayDuration, boolean finalGateChoice) {

        dot.getProperties().put("currentPhysicalFloor", currentLevel);
        updateDotVisibilityState(dot);

        Bounds curBounds = spotUI[currentLevel][0][0].getBoundsInParent();
        Bounds curLast   = spotUI[currentLevel][cols - 1][rows - 1].getBoundsInParent();
        double w = curBounds.getWidth();
        double h = curBounds.getHeight();

        double cLeftX   = curBounds.getMinX() - (w * 0.5);
        double cRightX  = curLast.getMaxX() + (w * 0.5);
        double cUpperY  = curBounds.getMinY() - (h * 0.815);
        double cLowerY  = curBounds.getMinY() - (h * 0.275);
        double cExitY   = curLast.getMaxY() + (h * 0.3);

        double cRampX = curLast.getMaxX() - (w * 0.5); //center of the last column

        Path descentPath = new Path();
        double duration;

        if (currentLevel == finalFloor) {
            descentPath.getElements().add(new MoveTo(cRightX, cLowerY)); //leaving the parking spot
            descentPath.getElements().add(new LineTo(cRightX, cUpperY)); //drive UP the top gate spine to exit the floor
            duration = TIME_ORIGIN_EXIT;

        } else if (currentLevel > 0) {
            descentPath.getElements().add(new MoveTo(cRampX, cUpperY)); //spawn exactly at the ramp tail (came from higher floor)
            descentPath.getElements().add(new LineTo(cLeftX, cUpperY));  //drive across the top aisle and loop the floor
            descentPath.getElements().add(new LineTo(cLeftX, cLowerY));
            descentPath.getElements().add(new LineTo(cRightX, cLowerY));  //drive UP the top gate spine to exit the floor
            descentPath.getElements().add(new LineTo(cRightX, cUpperY));
            duration = TIME_INTERMEDIATE_LOOP;

        } else {
            //alternate the gates (better exiting distribution)
            boolean exitTopRight = useTopRightExitNext;
            useTopRightExitNext = !useTopRightExitNext;

            //save the decision inside the dot so the final exit path knows which way to go
            dot.getProperties().put("exitTopRight", exitTopRight);

            descentPath.getElements().add(new MoveTo(cRampX, cUpperY));

            if (exitTopRight) {
                //THE LOOP PATH: force cars to traverse the floor before exiting top right
                descentPath.getElements().add(new LineTo(cLeftX, cUpperY));  //drive left across the top lane

                //U-TURN LOOP
                descentPath.getElements().add(new LineTo(cLeftX, cLowerY));  //drop down to the second lane
                descentPath.getElements().add(new LineTo(cRightX, cLowerY)); //drive right across the second lane

                descentPath.getElements().add(new LineTo(cRightX, cUpperY)); // Drive back up to the top-right exit gate

                // Use the loop duration so they don't travel at warp speed
                duration = TIME_INTERMEDIATE_LOOP;
                // Note: If you use the full perimeter loop above, you may want to do (TIME_INTERMEDIATE_LOOP * 2) here!

            } else {
                descentPath.getElements().add(new LineTo(cLeftX, cUpperY));  // Drive left to eventually exit bottom-left
                duration = TIME_GROUND_CROSS;
            }
        }

        PathTransition engine = new PathTransition(Duration.seconds(duration / Config.speedMultiplier), descentPath, dot);

        activeAnimations.add(engine); //TRACK DESCENT ANIMATION

        engine.setOnFinished(ev -> {
            activeAnimations.remove(engine);

            if (currentLevel > 0) {
                int nextLevel = currentLevel - 1;
                dot.getProperties().put("currentPhysicalFloor", nextLevel);
                updateDotVisibilityState(dot);
                chainDownwardRampDescent(dot, nextLevel, bottomRoadY, leftLaneX, rightLaneX, switchbackUpperY,
                        switchbackLowerY, v, finalFloor, finalCol, finalRow, rate, parkingStayDuration, finalGateChoice);
            } else {
                //retrieve the toggle decision we saved earlier
                boolean exitTopRight = (boolean) dot.getProperties().getOrDefault("exitTopRight", false);
                Path groundExitPath = new Path();

                if (exitTopRight) {
                    groundExitPath.getElements().add(new MoveTo(cRightX, cUpperY));
                    groundExitPath.getElements().add(new LineTo(cRightX, cUpperY)); //drive off top right gate
                } else {
                    groundExitPath.getElements().add(new MoveTo(cLeftX, cUpperY));
                    groundExitPath.getElements().add(new LineTo(cLeftX, cExitY)); //drive off bottom left gate
                }

                PathTransition finalOutEngine = new PathTransition(Duration.seconds(TIME_LOT_EXIT / Config.speedMultiplier), groundExitPath, dot);

                // --- TRACK FINAL EXIT ANIMATION ---
                activeAnimations.add(finalOutEngine);

                finalOutEngine.setOnFinished(eOut -> {
                    activeAnimations.remove(finalOutEngine);
                    completeCleanUp(v, finalFloor, finalCol, finalRow, rate, parkingStayDuration);
                });
                finalOutEngine.play();
            }
        });
        engine.play();
    }

    //==================================================================================================================

    //DATA UTILITIES & RESOURCE CLEANUP=================================================================================
    private void completeCleanUp(Vehicle v, int finalFloor, int finalCol, int finalRow, ParkRate rate, double parkingStayDuration) {
        Circle dot = v.getDot();

        if(Config.showDotGlow){
            v.endExitPulse();//turn off glow
        }

        if(logListener != null) {
            logListener.onLogEvent(dot.getFill(), v.getPlate(), false, finalRow, finalCol, finalFloor);
        }

        Tooltip.uninstall(dot, (Tooltip) dot.getProperties().get("tooltip"));
        dot.getProperties().clear();
        layeredCanvas.getChildren().remove(dot);

        recordVehicleData(v, rate, parkingStayDuration, finalFloor, finalCol, finalRow);

        int zoneWidth = (int) Math.ceil((double) cols / 3);
        int returnZoneId = Math.min(finalCol / zoneWidth, 2);
        floorStructuralZones.get(finalFloor).get(returnZoneId).add(new Point(finalCol, finalRow));
    }

    //vehicle checks which floor queue is necessary to go to depending on availability on that queued floor
    private FloorPoint checkMultiFloorTarget() {
        for (int f = 0; f < floors; f++) {
            int zonesInspected = 0;
            int temporaryTurn = activeZoneTurn;

            while (zonesInspected < 3) {
                Queue<Point> targetQueue = floorStructuralZones.get(f).get(temporaryTurn);
                if (!targetQueue.isEmpty()) {
                    activeZoneTurn = (temporaryTurn + 1) % 3;
                    Point p = targetQueue.poll();
                    return new FloorPoint(f, p.x, p.y);
                }
                temporaryTurn = (temporaryTurn + 1) % 3;
                zonesInspected++;
            }
        }
        return null;
    }

    //vehicle determines which correct aisle to go to before they park at the stall/cell
    private double determineAisleY(int targetRow, int targetCol, Bounds firstCellBounds) {
        if (targetRow == 0) {
            Bounds row0Bounds = spotUI[0][targetCol][0].getBoundsInParent();
            double row0TopY = row0Bounds.getMinY();
            return row0TopY - 18.0;
        } else {
            int rowAbove = (targetRow % 2 == 0) ? targetRow - 1 : targetRow;
            int rowBelow = rowAbove + 1;

            Bounds boundsAbove = spotUI[0][targetCol][rowAbove].getBoundsInParent();

            if (rowBelow >= rows) {
                double rowAboveBottomY = boundsAbove.getMaxY();
                return rowAboveBottomY + 12.5;
            }

            Bounds boundsBelow = spotUI[0][targetCol][rowBelow].getBoundsInParent();

            double bottomOfAboveRow = boundsAbove.getMaxY();
            double topOfBelowRow = boundsBelow.getMinY();

            return bottomOfAboveRow + ((topOfBelowRow - bottomOfAboveRow) / 2.0);
        }
    }

    //records all vehicle data (throughout the lifetime of the simulation, not the app)
    private void recordVehicleData(Vehicle v, ParkRate rate, double parkingStayDuration, int finalFloor, int finalCol, int finalRow) {

        v.setTotalDuration(parkingStayDuration);
        v.setExitTime(LocalTime.now());

        //calculates total time spent for the vehicle
        java.time.Duration totalTraverseAndParked = java.time.Duration.between(v.getEntryTime(), v.getExitTime());

        //MIDNIGHT ROLLOVER
        //if exit time (e.g., 00:00:12) is chronologically behind entry time (e.g., 23:59:25),
        //java calculates a negative duration in which adding 24 hours perfectly bridges the gap.
        if (totalTraverseAndParked.isNegative()) {
            totalTraverseAndParked = totalTraverseAndParked.plusDays(1);
        }

        double t = totalTraverseAndParked.toMillis() / 1000.0;

        //this specific window is the vehicle's total traversal time (exiting from and entering to spot)
        double tDuration = t - v.getTotalDuration();

        v.setTotalTraversalTime(tDuration);
        v.setAmountPaid(rate.processFeeRate(v));
        totalRevenue.set(totalRevenue.get() + v.getAmountPaid());

        String carDetails = String.format("[%s-%s]", v.getModel(), v.getType());
        String spot = String.format("[%d][%d][%d]", finalRow+1, finalCol+1, finalFloor+1);

        String logEntry = String.format(
                "EXIT @%s | Vehicle: %-8s %-30s | PAID: $%5.2f | STAYED: %6.2fs at %-12s + TOTAL TRAVERSAL: %6.2fs | ENTRY: %s | TICKET#: %d",
                v.getExitTime().format(logTimeFormatter),
                v.getPlate(),
                carDetails,
                v.getAmountPaid(),
                v.getTotalDuration(),
                spot,
                v.getTotalTraversalTime(),
                v.getEntryTime().format(logTimeFormatter),
                v.getTicketNumber()
        );

        //DESKTOP PATH & DELETE ON EXIT
        String desktopPath = System.getProperty("user.home") + File.separator + "Desktop" + File.separator + "vehicle_logs.txt";
        File logFile = new File(desktopPath);
        logFile.deleteOnExit();

        try (PrintWriter out = new PrintWriter(new FileWriter(logFile, true))) {
            out.println(logEntry);
        } catch (IOException e) {
            System.err.println("Error writing to log file: " + e.getMessage());
        }
    }

    //==================================================================================================================

    //GETTERS===========================================================================================================
    public Pane getLayeredPaneCanvas() { return layeredCanvas; }
    public DoubleProperty getRevenueProperty() { return totalRevenue; }
    public IntegerProperty getOccupancyProperty() { return currentOccupancy; }
    public IntegerProperty getTotalCars() { return totalCars; }
    public int getFloorCount() { return floors; }
    public int getMaxCapacity() { return rows * cols * floors; }

    //==================================================================================================================

    //ANIMATION STOP METHOD=============================================================================================
    public void stopAllActiveTimers() {
        for (javafx.animation.Animation anim : activeAnimations) {
            if (anim != null) {
                anim.stop();
            }
        }
        activeAnimations.clear();
    }
}